### ISSUE TITLE
Compatibility issue with Openfire 4.9.0

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-hazelcast-plugin#97]
Version 2.6.1 of the plugin is not compatible with Openfire 4.9.0. This error is logged when starting:

```
2024.08.23 14:11:10 ERROR [PluginMonitorTask-2]: org.jivesoftware.openfire.container.PluginMonitor - An unexpected exception occurred:
java.lang.NoSuchMethodError: 'java.lang.String org.jivesoftware.util.JiveGlobals.getHomeDirectory()'
        at org.jivesoftware.openfire.plugin.HazelcastPlugin.initializeClustering(HazelcastPlugin.java:83) ~[?:?]
        at org.jivesoftware.openfire.plugin.HazelcastPlugin.access$000(HazelcastPlugin.java:44) ~[?:?]
        at org.jivesoftware.openfire.plugin.HazelcastPlugin$1.pluginsMonitored(HazelcastPlugin.java:58) ~[?:?]
        at org.jivesoftware.openfire.container.PluginManager.firePluginsMonitored(PluginManager.java:1221) ~[xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginManager.firePluginsMonitored(PluginManager.java:1214) ~[xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask.run(PluginMonitor.java:416) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by akrherz** [comment]
fixed by #98
