### ISSUE TITLE
ClusteredCacheFactory - Unable to start clustering Invalid content was found starting with element

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-hazelcast-plugin#99]
Whilst attempting to get current snapshot hazelcast running on igniterealtime
```
2024.09.09 18:46:28 ESC[1;31mERRORESC[m [PluginMonitorExec-2]: org.jivesoftware.openfire.plugin.util.cache.ClusteredCacheFactory - Unable to start clustering - continuing in local mode
com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.hazelcast.com/schema/config":group}'. One of '{"http://www.hazelcast.com/schema/config":import, "http://www.hazelcast.com/schema/config":config-replacers, "http://www.hazelcast.com/schema/config":cluster-name, "http://www.hazelcast.com/schema/config":license-key, "http://www.hazelcast.com/schema/config":instance-name, "http://www.hazelcast.com/schema/config":management-center, "http://www.hazelcast.com/schema/config":properties, "http://www.hazelcast.com/schema/config":wan-replication, "http://www.hazelcast.com/schema/config":network, "http://www.hazelcast.com/schema/config":partition-group, "http://www.hazelcast.com/schema/config":executor-service, "http://www.hazelcast.com/schema/config":durable-executor-service, "http://www.hazelcast.com/schema/config":scheduled-executor-service, "http://www.hazelcast.com/schema/config":queue, "http://www.hazelcast.com/schema/config":map, "http://www.hazelcast.com/schema/config":multimap, "http://www.hazelcast.com/schema/config":replicatedmap, "http://www.hazelcast.com/schema/config":cache, "http://www.hazelcast.com/schema/config":list, "http://www.hazelcast.com/schema/config":set, "http://www.hazelcast.com/schema/config":topic, "http://www.hazelcast.com/schema/config":reliable-topic, "http://www.hazelcast.com/schema/config":ringbuffer, "http://www.hazelcast.com/schema/config":listeners, "http://www.hazelcast.com/schema/config":serialization, "http://www.hazelcast.com/schema/config":native-memory, "http://www.hazelcast.com/schema/config":security, "http://www.hazelcast.com/schema/config":member-attributes, "http://www.hazelcast.com/schema/config":split-brain-protection, "http://www.hazelcast.com/schema/config":lite-member, "http://www.hazelcast.com/schema/config":hot-restart-persistence, "http://www.hazelcast.com/schema/config":persistence, "http://www.hazelcast.com/schema/config":user-code-deployment, "http://www.hazelcast.com/schema/config":cardinality-estimator, "http://www.hazelcast.com/schema/config":flake-id-generator, "http://www.hazelcast.com/schema/config":crdt-replication, "http://www.hazelcast.com/schema/config":pn-counter, "http://www.hazelcast.com/schema/config":advanced-network, "http://www.hazelcast.com/schema/config":cp-subsystem, "http://www.hazelcast.com/schema/config":auditlog, "http://www.hazelcast.com/schema/config":metrics, "http://www.hazelcast.com/schema/config":instance-tracking, "http://www.hazelcast.com/schema/config":sql, "http://www.hazelcast.com/schema/config":jet, "http://www.hazelcast.com/schema/config":local-device, "http://www.hazelcast.com/schema/config":dynamic-configuration, "http://www.hazelcast.com/schema/config":integrity-checker, "http://www.hazelcast.com/schema/config":data-connection, "http://www.hazelcast.com/schema/config":tpc}' is expected.
        at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:120) ~[hazelcast-5.3.7.jar:5.3.7]
        at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:171) ~[hazelcast-5.3.7.jar:5.3.7]
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:153) ~[hazelcast-5.3.7.jar:5.3.7]
        at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:100) ~[hazelcast-5.3.7.jar:5.3.7]
        at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:64) ~[hazelcast-5.3.7.jar:5.3.7]
        at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:50) ~[hazelcast-5.3.7.jar:5.3.7]
        at org.jivesoftware.openfire.plugin.util.cache.ClusteredCacheFactory.startCluster(ClusteredCacheFactory.java:171) [hazelcast-3.0.0-SNAPSHOT.jar:?]
        at org.jivesoftware.util.cache.CacheFactory.startClustering(CacheFactory.java:859) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.cluster.ClusterManager.startup(ClusterManager.java:327) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.plugin.HazelcastPlugin.initializeClustering(HazelcastPlugin.java:87) [hazelcast-3.0.0-SNAPSHOT.jar:?]
        at org.jivesoftware.openfire.plugin.HazelcastPlugin$1.pluginsMonitored(HazelcastPlugin.java:58) [hazelcast-3.0.0-SNAPSHOT.jar:?]
        at org.jivesoftware.openfire.container.PluginManager.firePluginsMonitored(PluginManager.java:1221) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginManager.addPluginManagerListener(PluginManager.java:1141) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.plugin.HazelcastPlugin.initializePlugin(HazelcastPlugin.java:54) [hazelcast-3.0.0-SNAPSHOT.jar:?]
        at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:640) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:380) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:368) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Comment by iarwen** [comment]
It looks like you add a <group> on hazelcast-local-config.xml, if you want to upgrade to hazelcast-5.3.7.jar, that is a invalid config now. 
5.3.7 use `<cluster-name>` instead of `<group><name>SOME-NAME</name></group>`, and  I had hard code cluster as `openfire-cluster-by-hazelcast` on hazelcast-cache-config.xml, see  https://github.com/igniterealtime/openfire-hazelcast-plugin/blob/main/classes/hazelcast-cache-config.xml

**Comment by guusdk** [comment]
Correct. I had already mentioned this in the readme of version 3.0.0 of the plugin, and in the release notes.

**Comment by guusdk** [comment]
I'm closing this issue, as I'm not sure we'll be programmatically prevent this from happening.
